# Gradle Project settings
projectName = entraidprovider

# XP App values
appDisplayName = Entra ID Provider
appName = com.enonic.app.entraidprovider
vendorName = Enonic AS
vendorUrl = https://enonic.com
xpVersion = 8.0.3

# Settings for publishing to a Maven repo
group = com.enonic.app
version=4.1.0-SNAPSHOT
