= Migration from Azure ID provider
:imagesdir: media/

This guide describes how to migrate from the legacy `com.enonic.app.azureadidprovider.cfg` configuration format to the new Entra ID Provider configuration structure `com.enonic.app.entraidprovider.cfg`.

== Migrating Core Configuration

=== Removed properties
[source,ini]
----
idprovider.<name>.tenantId=
idprovider.<name>.logoutUrl=
idprovider.<name>.forceHttpsOnRedirectUri=
idprovider.<idprovidername>.user.name=
idprovider.<idprovidername>.user.displayName=
idprovider.<idprovidername>.user.email=
----

=== New

NOTE:: The ID provider configuration supports Microsoft identity platform v2.0 endpoints.

==== Replacement for `tenantId`

The `tenantId` property is no longer used. You should use `oidcWellKnownEndpoint` instead. This approach is recommended for all new configurations, as the properties `issuer`, `authorizationUrl`, `tokenUrl`, `userinfoUrl`, and `jwksUri` will then be populated automatically.

[source,ini]
----
idprovider.<name>.oidcWellKnownEndpoint=https://login.microsoftonline.com/<tenantid>/v2.0/.well-known/openid-configuration
----

Alternatively, explicit endpoints can be set:

[source,ini]
----
idprovider.<name>.issuer=https://login.microsoftonline.com/<tenantid>/v2.0

idprovider.<name>.authorizationUrl=https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/authorize
idprovider.<name>.tokenUrl=https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token
idprovider.<name>.userinfoUrl=https://graph.microsoft.com/oidc/userinfo
idprovider.<name>.jwksUri=https://login.microsoftonline.com/<tenantid>/discovery/v2.0/keys
----

NOTE:: `<tenantid>` must be replaced with a real tenant identifier in the configuration.

or if you plan to use a multi-tenant configuration:

----
idprovider.<name>.oidcWellKnownEndpoint=https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration
----

Alternatively, explicit endpoints can be set:

[source,ini]
----
idprovider.<name>.issuer=https://login.microsoftonline.com/{tenantid}/v2.0

idprovider.<name>.authorizationUrl=https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
idprovider.<name>.tokenUrl=https://login.microsoftonline.com/organizations/oauth2/v2.0/token
idprovider.<name>.userinfoUrl=https://graph.microsoft.com/oidc/userinfo
idprovider.<name>.jwksUri=https://login.microsoftonline.com/organizations/discovery/v2.0/keys
----

Use `*` if you want to allow any tenant, but this is not recommended. Otherwise, use space-separated tenant IDs.

[source,ini]
----
idprovider.<name>.allowedTenants=tenantid_1 tenantid_2 tenantid_3
----

NOTE:: In the source code, `{tenantid}` will be replaced with the `tid` claim extracted from a JWT token.

==== Replacement for `logoutUrl`

The `logoutUrl` property is no longer used. You should use `endSession.url` instead.

[source,ini]
----
idprovider.<name>.endSession.url=https://login.microsoftonline.com/common/oauth2/v2.0/logout
----

==== Replacement for `forceHttpsOnRedirectUri`

This property is not supported by this ID provider.

==== Replacement for `user...`

The `user.name` property is no longer used. You should use `claimUsername` instead. The default value is `oid`, which is extracted from the JWT token and serves as a unique and immutable user identifier.

[source,ini]
----
idprovider.<name>.claimUsername=
----

The `user.displayName` and `user.email` properties are no longer used. You should use `mappings.displayName` and `mappings.email` instead.

[source,ini]
----
idprovider.<name>.mappings.displayName=
idprovider.<name>.mappings.email=
----

==== `groupPrefix`

The `groupPrefix` property allows you to specify a prefix for Enonic XP groups to which the user will be added. The default value is `azure-ad-` for backward compatibility.

==== User events

The new version of the ID provider supports the same user events but allows you to customize the event prefix. The default value is the name of the current application, taken from the global JavaScript variable `app.name`.

[source,ini]
----
idprovider.<name>.userEventPrefix=myapp
idprovider.<name>.userEventMode=off|local|distributed
----

In this version, the ID provider introduces the ability to control how user events are delivered locally, across the cluster, or disabled entirely. Default value is `local`.

[source,ini]
----
idprovider.<name>.userEventMode=off|local|distributed
----

== Properties with usage restrictions

The `defaultGroups` and `forceEmailVerification` properties are not supported by the Entra ID Provider.

== Full Migration Example

=== Old configuration
[source,ini]
----
autoinit=true
idprovider.azure.tenantId= <your-tenant-id>
idprovider.azure.clientId= <your-client-id>
idprovider.azure.clientSecret= <your-client-secret>
idprovider.azure.logoutUrl=https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=https://yourdomain.com
idprovider.azure.createAndUpdateGroupsOnLoginFromGraphApi=true
idprovider.azure.user.name=@@{oid}
idprovider.azure.user.displayName=@@{given_name} @@{family_name}
idprovider.azure.user.email=@@{email}
idprovider.azure.forceHttpsOnRedirectUri=true
----

=== New configuration
[source,ini]
----
autoinit=true
idprovider.azure.oidcWellKnownEndpoint=https://login.microsoftonline.com/<your-tenant-id>/v2.0/.well-known/openid-configuration
idprovider.azure.clientId=<your-client-id>
idprovider.azure.clientSecret=<your-client-secret>

idprovider.azure.createAndUpdateGroupsOnLoginFromGraphApi=true

idprovider.azure.claimUsername=oid
idprovider.azure.mappings.displayName=@@{userinfo.given_name} @@{userinfo.family_name}
idprovider.azure.mappings.email=@@{userinfo.email}

idprovider.azure.endSession.url=https://login.microsoftonline.com/<your-tenant-id>/oauth2/v2.0/logout
idprovider.azure.endSession.postLogoutRedirectUriKey=https://yourdomain.com
----
